# Generated by Django 5.0.1 on 2024-02-10 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_slug'),
        ('products', '0007_product_slug'),
    ]

    operations = [
    ]
