# Generated by Django 5.0.1 on 2024-02-10 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20191016_2207'),
        ('products', '0009_product_timestamp_alter_product_slug'),
    ]

    operations = [
    ]
